# Generated by Django 5.1.7 on 2025-03-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.CharField(default='', max_length=6000),
            preserve_default=False,
        ),
    ]
