# Generated by Django 5.1.7 on 2025-04-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_description_alter_notes_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(choices=[('Fundamentals of Data Analytics', 'Fundamentals of Data Analytics'), ('Introduction to Mobile Computation', 'Introduction to Mobile Computation'), ('Mobile Application Development Using Android', 'Mobile Application Development Using Android'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Internet of Things', 'Internet of Things'), ('Project', 'Project')], max_length=600),
        ),
    ]
